#=======================================#
# Make Custom Desktop Environment from  #
#		Window Manager          #
#=======================================#

# Table of Contents
#	- Ingredients
#	- Recipes

#[Variables]

PKG_MGR="pacman"
CC="cc"


#[Ingredients]
pkgs: ## All Packages to install
	xorg xorg-xinit

#[Recipes]
default: ## Set Default Recipe 
	## What to do if no instructions
	make -c help

help: ## List all options
	install : install packages
	setup : 
	clean : 
	help : 
	default : 

install: ## Install Packages
	

setup: ## Generate and Setup Configs of programs
	

clean: ## Clean-up and remove all unnecessary files
	rm -f *.o